# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: riva_asr.proto for package 'nvidia.riva.asr'

require 'grpc'
require_relative 'riva_asr_pb'

module Nvidia
  module Riva
    module Asr
      module RivaSpeechRecognition
        # Service for automatic speech recognition
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'nvidia.riva.asr.RivaSpeechRecognition'

          # Streaming speech recognition
          rpc :StreamingRecognize, stream(::Nvidia::Riva::Asr::StreamingRecognizeRequest), stream(::Nvidia::Riva::Asr::StreamingRecognizeResponse)
          # Non-streaming speech recognition
          rpc :Recognize, ::Nvidia::Riva::Asr::RecognizeRequest, ::Nvidia::Riva::Asr::RecognizeResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
